# Generated by Django 5.2.5 on 2025-08-28 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(db_column='T001IdPersona', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T001Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='T001Apellido', max_length=100)),
                ('documento', models.CharField(db_column='T001Documento', max_length=20, unique=True)),
                ('email', models.EmailField(db_column='T001Email', max_length=254, unique=True)),
                ('activo', models.BooleanField(db_column='T001Activo', default=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'T001Persona',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.AutoField(db_column='T002IdTarea', editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='T002Titulo', max_length=200)),
                ('descripcion', models.TextField(db_column='T002Descripcion')),
                ('fecha_limite', models.DateField(db_column='T002FechaLimite')),
                ('persona', models.ForeignKey(db_column='T002PersonaId', on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='api_app.persona')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'T002Tarea',
            },
        ),
    ]
